### ISSUE TITLE
Installation failed because com.github.corna.Vivado.svg is not square

### ISSUE THREAD

**Issue by nikAizuddin** [corna/com.github.corna.Vivado.icons#1]
Hi,

I tried to install Vivado from source using the following command:
```
flatpak run org.flatpak.Builder --user --install --force-clean build-dir com.github.corna.Vivado.yml
```

But I got the following error:
```
error: /path/to/com.github.corna.Vivado/build-dir/export/share/icons/hicolor/scalable/apps/com.github.corna.Vivado.svg is not a valid icon: Expected a square icon but got: 165x169
```

Can you update the [hicolor/scalable/apps/com.github.corna.Vivado.svg](https://github.com/corna/com.github.corna.Vivado.icons/blob/484fc337f37055145f15de8eb162adcd0e5b742a/hicolor/scalable/apps/com.github.corna.Vivado.svg) icon and make it square resolution?

**Comment by corna** [comment]
Done in 5923e7a
